name: My First GitHub Actions Pipeline

on:
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Good Morning
        run: echo "Good Morning Bhargav!"

      - name: Congratulations
        run: echo "This is your first GitHub Actions pipeline. Congratulations! 🎉"
